 - name: create temporary build directory
   tempfile:
     suffix: build
     state: directory
   register: temporary_www_folder

 - debug:
    msg: "Using {{ temporary_www_folder }} has build folder"

 - name: Cloning web sources into temporary folder
   git: repo={{ git_web_repository }}
        dest={{temporary_www_folder.path}}
        version=master
        accept_hostkey=true

 - name: Installing React dependancies
   npm: path={{ temporary_www_folder.path }}
       production=yes

 - name: Build the application production version
   shell: npm run build
   args:
      chdir: "{{ temporary_www_folder.path }}"

 - name: Removing old nginx_folder
   file:
     path={{ nginx_folder }}
     state=absent
   become: true

 - name: Recreating the folder to empty it
   file:
     path={{ nginx_folder }}
     state=directory
   become: true

 - name: Copy project and dependancies into final folder
   shell: cd {{temporary_www_folder.path}} && mv ./build/* {{ nginx_folder }}/
   become: true
