- name: Getting MongoDB official repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927
  become: true

- name: MongoDB list
  shell: echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: Resynchronize the package index files (apt-get update)
  apt: update_cache=yes
  become: true

- name: Install mondodb
  apt: name=mongodb-org state=present
  become: true

- name: Create MongoDB dump directory
  become: true
  file:
    path: "{{ mongodump_directory }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Create a custom data directory for mongodb
  become: true
  file:
    path: "{{ mongo_data_directory }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Create log directory for mongodb
  become: true
  file:
    path: "{{ mongo_log_directory }}"
    state: directory
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Create log file for mongodb
  become: true
  file:
    path: "{{ mongo_log_directory }}/mongodb.log"
    state: touch
    owner: "{{ remote_user }}"
    group: "{{ remote_user }}"

- name: Create the mongodb startup file
  become: true
  template:
    dest: "{{ mongod_conf }}"
    src: mongod.conf.j2
    mode: 0655

- name: Set systemd file
  become: true
  template:
    dest: "{{ mongo_service }}"
    src: mongodb.service.j2

- name: Enable mongod systemd service and start it
  become: true
  systemd:
    daemon_reload: yes
    name: mongodb
    state: started
    enabled: yes
