site_domain: 'dev-onmy.travel'
site_api_subdomain: 'api.dev-onmy.travel'

api_configuration_file: '/etc/nginx/sites-available/api.onmy.travel'
site_configuration_file: '/etc/nginx/sites-available/onmy.travel'
nginx_configuration_file: '/etc/nginx/nginx.conf'

local_ssl_dir: '../../..'
local_ssl_keypath: '{{local_ssl_dir}}/certificates/nginx.key'
local_ssl_certificate: '{{local_ssl_dir}}/certificates/nginx.crt'

certificate_folder: '/etc/nginx/certificates'
ssl_keyfile_path: '{{ certificate_folder }}/nginx.key'
ssl_certificate_path: '{{ certificate_folder }}/nginx.crt'

nginx_error_path: '/var/log/nginx'
nginx_error_file: '{{nginx_error_path}}/error.log'
