- name: Create the ansible user
  user: name={{ item }}
  with_items:
    - "{{ remote_user }}"

- name: Create an authorized_keys file for the Ansible user
  authorized_key:
    user: "{{ remote_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub' )}}"

- name: Give ansible sudoer privilege
  lineinfile: dest=/etc/sudoers state=present line="{{remote_user}} ALL=(ALL) NOPASSWD:ALL"
