# Playbook
# Let's set-up the server
# (same users, groups, etc ...)
- hosts: master
  remote_user: ansible
  roles:
    - { role: base/secu, tags: 'secu' }
    - { role: base/nginx, tags: 'nginx' }
    - { role: base/mongodb, tags: 'mongodb' }
    - { role: base/node, tags: 'node' }
