# Playbook
# Let's set-up the server
# (same users, groups, etc ...)
- hosts: master
  remote_user: ansible
  roles:
    - { role: secu, tags: 'secu' }
    - { role: nginx, tags: 'nginx' }
    - { role: mongodb, tags: 'mongodb' }
    - { role: node, tags: 'node' }
