# Playbook
# We upgrade the local vagrant to reach the production state
# (same users, groups, etc ...)

- hosts: before_setup
  gather_facts: False

  tasks:
  - name: Installing python 2.x for Ansible
    become: yes
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- hosts: before_setup
  remote_user: vagrant
  become: yes
  roles:
    - { role: base/users, tags: 'users' }
    - { role: base/ssh, tags: 'ssh' }
